spring:
  application:
    name: ecommerce_dev
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  graphql:
    graphiql:
      enabled: true
    schema:
      locations: classpath:graphql/
      file-extensions: .graphqls

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: profile, email
        provider:
          google:
            user-name-attribute: sub

app:
  jwt:
    secret: ${APP_JWT_SECRET}
    expiration-ms: 86400000
  oauth2:
    redirect-uri: ${OAUTH2_REDIRECT_URI}

springdoc:
  swagger-ui:
    enabled: true

logging:
  level:
    org.ecommerce.v1: DEBUG
    org.springframework.security: INFO